name: "Lock"
description: "Implements a named lock with auto release, wraps github/lock"
inputs:
  name:
    description: "Name of the lock"
    required: true
  mode:
    description: "lock/unlock"
    default: "lock"
  github_token:
    description: "GitHub Token"
    default: ${{ github.token }}
  auto_unlock:
    description: "Unlock after workflow done"
    default: true
  fail_if_cant_lock:
    description: "Fail if can't lock"
    default: true
  fail_if_cant_unlock:
    description: "Fail if can't unlock"
    default: true
outputs:
  locked:
    description: "If lock was acquired"
  released:
    description: "If lock was released"
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/post/index.js"
  post-if: ${{ steps.main.outputs.locked == "true" }}
  # post-if: success() && ${{ inputs.auto_unlock == "true" }} && ${{ steps.main.outputs.locked == "true" }}
