name: "Lock"
description: "Implements a named lock with auto release, wraps github/lock"
inputs:
  name:
    description: "Name of the lock"
    required: true
  mode:
    description: "lock/unlock"
    required: "lock"
  github_token:
    description: "GitHub Token"
    default: ${{ github.token }}
  autounlock:
    description: "Unlock after workflow done"
    default: true
outputs:
  locked:
    description: "If lock was acquired"
  released:
    description: "If lock was released"
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/post/index.js"
  post-if: success()
