name: Test

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Lock with no 
        uses: sahlet-official/lock@v0.0.61
        with:
          name: test
          : false

      - name: Lock second time
        uses: sahlet-official/lock@v0.0.61
        with:
          name: test
          : false

      - name: unlock
        uses: sahlet-official/lock@v0.0.61
        with:
          name: test
          mode: unlock

      - name: with 
        uses: sahlet-official/lock@v0.0.61
        with:
          name: test